version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ~/.custom_docker_data/mongo:/data/db
    ports:
      - 27017:27017
  backend:
    build: .
    env_file:
      - .env
