"""kafka offset

Revision ID: da484a707b86
Revises: 5bad5c4d6530
Create Date: 2023-10-08 16:44:26.722045

"""
from typing import Sequence, Union

import sqlalchemy
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'da484a707b86'
down_revision: Union[str, None] = '5bad5c4d6530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

kafka_offset_table = sa.table(
    "kafka_offset",
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offset', sa.BIGINT(), nullable=True),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kafka_offset',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('offset', sa.BIGINT(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.bulk_insert(
        kafka_offset_table,
        [
            {"id": 0, "offset": "0"}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kafka_offset')
    # ### end Alembic commands ###
