"""follow count schema

Revision ID: fe09a0828d31
Revises: 
Create Date: 2023-09-19 12:34:45.047389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe09a0828d31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_count',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('following_count', sa.BIGINT(), nullable=True),
    sa.Column('follower_count', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_count')
    # ### end Alembic commands ###
